# Use an official Python runtime as a parent image
FROM python:3.11.4-slim-buster

WORKDIR /app

COPY . /app

RUN pip install --trusted-host pypi.python.org -r requirements.txt

EXPOSE 8000

ENV UVICORN_WORKERS=1

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
