FROM public.ecr.aws/lambda/python:3.8

COPY lambda_function.py /var/task/
COPY your_model.pkl /var/task/

# Set environment variables
ENV AWS_LAMBDA_FUNCTION_NAME=lambda_function
ENV AWS_LAMBDA_FUNCTION_MEMORY_SIZE=256

CMD ["lambda_function.lambda_handler"]
