# Use the official AWS Lambda base image for Python 3.11
FROM public.ecr.aws/lambda/python:3.11

# Set the working directory
WORKDIR /app

# Install dependencies (if any)
COPY ./app/requirements.txt . 
RUN pip install -r requirements.txt

# Copy the Lambda function code and model file into the image
COPY ./app/lambda_function.py .
COPY ./app/rf_pipeline.pkl .

# Define the Lambda handler
CMD ["lambda_function.lambda_handler"]
